default_stages: [
    commit,
    merge-commit,
    push,
    prepare-commit-msg,
    commit-msg,
    post-checkout,
    post-commit,
    post-merge,
    post-rewrite
]
repos:
-   repo: local
    hooks:
    # NOTE: we make `black` a local hook because if it's installed from
    # PyPI (rather than from source) then it'll run twice as fast thanks to mypyc
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]
        additional_dependencies: [black]
