[project]
name = "prkknot"
version = "0.0.0"
description = "Flex-Knot reconstruction of dark energy PR(k), for use with Cobaya"
authors = [{name="Adam Neil Ormondroyd", email="Adam.Ormondroyd@gmail.com"}]
readme = "README.md"
dependencies = ["numpy", "cobaya", "linf@git+ssh://github.com/Ormorod/linf@main", "anesthetic", "fgivenx"]

[project.urls]
repository = "https://github.com/Ormorod/prkknot"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["black"]
