name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Upgrade pip and install linters
      run: |
        python -m pip install --upgrade pip
        python -m pip install "black"
    - name: black compliance checks
      run: python -m black . --check

  pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [ubuntu-latest]
            python-version: '3.9'
          - os: [macos-latest]
            python-version: '3.10'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
